### ISSUE TITLE
FriendsViewerPlugin ClassCastException

### ISSUE THREAD

**Issue by YvesW** [molo-pl/runelite-plugins#5]
FYI the API got updated this week, so https://github.com/molo-pl/runelite-plugins/blob/a5655ae927bc9f872af7bec25e7c9aa7a948bafe/src/main/java/com/molopl/plugins/friendsviewer/FriendsViewerPlugin.java#L192 will result in a ClassCastException.

**Comment by camschnackel** [comment]
Really hope this plugin hasn't been abandoned, but it's now been a couple weeks of it being broken.

**Comment by molo-pl** [comment]
I'll look into it as soon as time allows (probably this week).

**Comment by molo-pl** [comment]
Fixed in https://github.com/runelite/plugin-hub/pull/6586
